1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [3]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
a

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [5]:
U, s, W = np.linalg.svd(a)

U, s, W.T

(array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
        [ 0.39, -0.53,  0.61, -0.43,  0.03],
        [-0.14, -0.82, -0.52,  0.14,  0.07],
        [ 0.89,  0.06, -0.25,  0.38, -0.06],
        [ 0.08,  0.11, -0.08, -0.11,  0.98]]),
 array([8.82, 6.14, 2.53]),
 array([[ 0.07, -0.37, -0.93],
        [ 0.72,  0.67, -0.21],
        [ 0.69, -0.65,  0.31]]))

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [10]:
np.linalg.norm(a, ord=2)

8.824868854820444

In [9]:
np.linalg.norm(a)

11.045361017187261

Евклидова норма: 8.824868854820444

норма Фробениуса: 11.045361017187261