## Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### 1. 
а) Произведение не определено

б) Произведение не определено

в) Произведение определено, размерность: 8x8

г) Произведение определено, размерность: 4x4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

#### 2. Решение в pdf

In [2]:
import numpy as np

a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

a+b

array([[ 5, -3],
       [ 3,  5]])

In [4]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

#### 3. Решение в pdf

In [8]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

In [9]:
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

#### 4. Решение в pdf

In [11]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [12]:
np.dot(a, a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [13]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])

## Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

#### 1. Решение в pdf

In [18]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)

180.0

In [19]:
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(v)

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
 

#### 2. Решение 
- a) = det(A) * det(A) = 16
- б) = det(A) = 4
- в) = det(A) * 2 = 8

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



#### 3. Решение

Все элементы второй строки = -2 * все элементы первой строки => матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

#### 4. Решение

а) Третья строка = первая + вторая. Следовательно, максимальный размер матрицы, где определитель не равень 0 - 2x2. Ранг = 2

In [23]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

б) Второй столбец линейно зависим первому и равен x1.5. Следовательно, ранг = 4-1 = 3

In [25]:
b=np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(b)

3